version: "3"
networks:
  nocobase:
    driver: bridge
services:
  postgres:
    image: postgres:latest
    restart: always
    networks:
      - nocobase
    command: postgres -c wal_level=logical
    ports:
      - "${DB_POSTGRES_PORT}:5432"
    volumes:
      - ./storage/db/postgres/backups:/backups
    environment:
      POSTGRES_USER: ptipu
      POSTGRES_DB: ptipu
      POSTGRES_PASSWORD: ptipu
  nocobase:
    build:
      dockerfile:  Dockerfile
      context: .
    networks:
      - nocobase
    command: [ "yarn", "start" ]
    working_dir: /app
    env_file: ./.env
    volumes:
      - ./:/app
    expose:
      - ${APP_PORT}
    ports:
      - "${APP_PORT}:${APP_PORT}"
