version: "3"
networks:
  nocobase:
    driver: bridge

services:
  postgres:
    image: postgres:latest
    restart: always
    networks:
      - nocobase
    command: postgres -c wal_level=logical
    environment:
      POSTGRES_USER: ptipu
      POSTGRES_DB: ptipu
      POSTGRES_PASSWORD: ptipu
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ptipu"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "${DB_POSTGRES_PORT:-5432}:5432"

  nocobase:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - nocobase
    command: ["yarn", "start"]
    working_dir: /app
    env_file: ./.env
    volumes:
      - ./:/app
    ports:
      - "${APP_PORT}:${APP_PORT}"
